// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

type AddContactPageData struct{}

func AddContactPageBody(c context.Context, data AddContactPageData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := `
		/* Twitter-inspired Theme */
		@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap');

		.contacts-container {
			max-width: 800px;
			margin: 0 auto;
			text-align: center;
			background-color: #15202b; /* Twitter Dark Mode background color */
			color: #ffffff; /* Light text color */
			font-family: 'Roboto', sans-serif; /* Use Google Font */
		}

		.search-form {
			margin-bottom: 20px;
		}

		.search-form input,
		.search-form button {
			padding: 8px;
			background-color: #192734; /* Twitter Dark Mode input background color */
			color: #ffffff; /* Light text color */
			border: 1px solid #38444d; /* Twitter Dark Mode input border color */
		}

		.search-form button {
			cursor: pointer;
		}

		.add-contact-form {
			margin-bottom: 20px;
			padding: 20px;
			background-color: #1c2938; /* Twitter Dark Mode form background color */
			border: 1px solid #38444d; /* Twitter Dark Mode form border color */
			border-radius: 8px;
			text-align: left;
		}

		.add-contact-form label {
			display: block;
			margin-bottom: 8px;
			color: #ffffff; /* Light text color */
		}

		.add-contact-form input {
			width: 100%;
			padding: 8px;
			margin-bottom: 16px;
			background-color: #192734; /* Twitter Dark Mode input background color */
			color: #ffffff; /* Light text color */
			border: 1px solid #38444d; /* Twitter Dark Mode input border color */
		}

		.add-contact-form button {
			padding: 8px 16px;
			background-color: #1da1f2; /* Twitter Blue button color */
			color: #ffffff; /* Light text color */
			border: none;
			border-radius: 4px;
			cursor: pointer;
		}

		.contacts-table {
			width: 100%;
			border-collapse: collapse;
		}

		.contacts-table th,
		.contacts-table td {
			padding: 12px;
		}

		.contacts-table th {
			background-color: #1c2938; /* Twitter Dark Mode header background color */
			color: #ffffff; /* Light text color */
		}

		.contacts-table a {
			color: #1da1f2; /* Twitter Blue link color */
		}

		.add-contact-link {
			margin-top: 20px;
		}

		.action-link {
			color: #1da1f2; /* Twitter Blue action link color */
			margin-right: 10px;
		}
	`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</style><div class=\"contacts-container\"><form action=\"/contacts/new\" method=\"post\" class=\"add-contact-form\"><label for=\"firstName\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := `First Name:`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</label> <input type=\"text\" id=\"firstName\" name=\"firstName\" required> <label for=\"lastName\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := `Last Name:`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</label> <input type=\"text\" id=\"lastName\" name=\"lastName\" required> <label for=\"phone\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var5 := `Phone:`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</label> <input type=\"tel\" id=\"phone\" name=\"phone\" required> <label for=\"email\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var6 := `Email:`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</label> <input type=\"email\" id=\"email\" name=\"email\" required> <button type=\"submit\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var7 := `Add Contact`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
